In [3]:
#1. Generate marks for 50 students
import numpy as np
marks=np.random.randint(0,101,50)
marks

array([ 52,  87,  82,  49,  17,   1,  50,  99,  27,   5,  35,   1,  43,
        13,  15, 100,  25,  13,   5,  87,  77,  82,  99,  22,  99,   7,
        44,  21,  44,  23,  23,  86,   6,  86,  29,   0,  81,   3,  32,
        92,  53,  68,  24,  63,  67,  48,  92,  56,  20,  49], dtype=int32)

In [4]:
#2. Calculate total, average, highest, lowest.
print("total marks:",marks.sum())
print("average marks:",marks.mean())
print("highest marks:",marks.max())
print("lowest marks:",marks.min())

total marks: 2302
average marks: 46.04
highest marks: 100
lowest marks: 0


In [5]:
#3. Count above 75, below 35, between 35-75.
above_75=np.sum(marks>75)
below_35=np.sum(marks<35)
between=np.sum((marks>35)&(marks<75))
print("above 75:",above_75)
print("above 35:",below_35)
print("between 35-75:",between)

above 75: 14
above 35: 22
between 35-75: 13


In [6]:
#4. Assign grades.
grade=[]
for i in marks:
    if i >=90:
        grade.append("A+")
    elif i >= 75:
        grade.append("A")
    elif i >= 60:
        grade.append("B")
    elif i >= 35:
        grade.append("C")
    else:
        grade.append("F")
print(grade)

['C', 'A', 'A', 'C', 'F', 'F', 'C', 'A+', 'F', 'F', 'C', 'F', 'C', 'F', 'F', 'A+', 'F', 'F', 'F', 'A', 'A', 'A', 'A+', 'F', 'A+', 'F', 'C', 'F', 'C', 'F', 'F', 'A', 'F', 'A', 'F', 'F', 'A', 'F', 'F', 'A+', 'C', 'B', 'F', 'B', 'B', 'C', 'A+', 'C', 'F', 'C']


In [8]:
#5. Display top 5 marks.
sorted_marks = np.sort(marks)
top5 = sorted_marks[-5:]
print("\nTop 5 Marks:")
print(top5[::-1])


Top 5 Marks:
[100  99  99  99  92]


In [9]:
#6. Display Bottom 5 Marks
sorted_marks = np.sort(marks)
bottom5 = sorted_marks[:5]
print("\nBottom 5 Marks:")
print(bottom5)


Bottom 5 Marks:
[0 1 1 3 5]


In [10]:
#7. Find median and standard deviation
print("median of marks:",np.median(marks))
print("standard deviation:",np.std(marks))

median of marks: 44.0
standard deviation: 32.14775886434387


In [11]:
#8. Create 5-subject marks matrix and calculate totals
marks = np.random.randint(35, 101, (10, 5))
print("Marks Matrix:")
print(marks)
totals = np.sum(marks, axis=1)
print("\nTotal Marks of Each Student:")
print(totals)

Marks Matrix:
[[76 40 76 92 91]
 [97 57 90 77 95]
 [45 75 42 72 46]
 [68 96 82 65 44]
 [75 77 63 45 63]
 [90 90 93 70 56]
 [54 64 71 47 43]
 [89 36 59 60 35]
 [48 71 46 50 85]
 [57 43 41 38 51]]

Total Marks of Each Student:
[375 416 280 355 323 399 279 279 300 230]


In [12]:
#9. Find topper in each subject.
topper = np.max(marks, axis=0)
print("\nHighest Marks in Each Subject:")
print(topper)


Highest Marks in Each Subject:
[97 96 93 92 95]


In [13]:
#10. Generate report card with Total, Average, Percentage and Grade
import numpy as np
marks = np.random.randint(35, 101, (10, 5))
print("Marks Matrix:")
print(marks)
total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)
percentage = average
print("\nReport Card")
print("-" * 55)
print("Student\tTotal\tAverage\tPercentage\tGrade")
for i in range(len(total)):
    if percentage[i] >= 90:
        grade = "A+"
    elif percentage[i] >= 75:
        grade = "A"
    elif percentage[i] >= 60:
        grade = "B"
    elif percentage[i] >= 35:
        grade = "C"
    else:
        grade = "F"
    print(f"{i+1}\t{total[i]}\t{average[i]:.2f}\t{percentage[i]:.2f}%\t\t{grade}")

Marks Matrix:
[[51 71 76 69 35]
 [79 60 94 68 83]
 [46 41 51 40 36]
 [38 46 39 63 57]
 [71 74 47 39 91]
 [97 78 39 71 55]
 [87 54 71 52 62]
 [68 83 42 56 82]
 [88 99 90 76 92]
 [49 68 76 77 85]]

Report Card
-------------------------------------------------------
Student	Total	Average	Percentage	Grade
1	302	60.40	60.40%		B
2	384	76.80	76.80%		A
3	214	42.80	42.80%		C
4	243	48.60	48.60%		C
5	322	64.40	64.40%		B
6	340	68.00	68.00%		B
7	326	65.20	65.20%		B
8	331	66.20	66.20%		B
9	445	89.00	89.00%		A
10	355	71.00	71.00%		B
